name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Checks relating to the linting of files
  lint:
    runs-on: ubuntu-latest

    permissions:
      # Report GitHub Commit status
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          # Full git history needed to get proper list of changed files within super-linter
          fetch-depth: 0
          # Don't keep GITHUB_TOKEN on filesystem
          persist-credentials: false

      - name: Check
        uses: github/super-linter/slim@v7
        env:
          # Lint only changed files
          VALIDATE_ALL_CODEBASE: false
          # Exclude `pull_request_template.md` since it doesn't meet MD041/first-line-heading
          # Exclude `icons/{circle,square}/` to reduce scan time when `VALIDATE_ALL_CODEBASE: true`
          # since nothing in them is linted
          FILTER_REGEX_EXCLUDE: '\.github/pull_request_template\.md|icons/(circle|square)/'

          # Linter config files paths are relative to repo root
          LINTER_RULES_PATH: "."
          # Report GitHub Commit status
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Linters
          VALIDATE_PYTHON_FLAKE8: true

          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: '.github/workflows/markdownlint-config.json'

          VALIDATE_EDITORCONFIG: true
          EDITORCONFIG_FILE_NAME: '.editorconfig'


  # Checks relating to the database
  check:
    name: check database

    # minimal permissions
    permissions: {}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          # Don't keep GITHUB_TOKEN on filesystem
          persist-credentials: false

      - name: Check database
        run: |
          python3 ./tests/schema.py
          python3 ./tests/db_entry.py
          python3 ./tests/icons_entry.py
          python3 ./tests/ordered_db.py
          python3 ./tests/icon_cache.py
          python3 ./tests/duplicates.py
